# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x08sentinel\"\x90\x01\n\x0c\x43hunkRequest\x12\x0c\n\x04repo\x18\x01 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\r\n\x05patch\x18\x04 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x05 \x01(\t\x12\x13\n\x0breceived_at\x18\x06 \x01(\x01\x12\x13\n\x0b\x63hunk_index\x18\x07 \x01(\x05\"\xda\x01\n\x0eReviewResponse\x12\x0c\n\x04repo\x18\x01 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x0c\n\x04line\x18\x04 \x01(\x05\x12\x10\n\x08severity\x18\x05 \x01(\t\x12\x13\n\x0bseverity_id\x18\x06 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x07 \x01(\t\x12\x0f\n\x07message\x18\x08 \x01(\t\x12\x12\n\nconfidence\x18\t \x01(\x01\x12\x17\n\x0fidempotency_key\x18\n \x01(\t\x12\x13\n\x0breceived_at\x18\x0b \x01(\x01\x32S\n\x10InferenceService\x12?\n\x0bReviewChunk\x12\x16.sentinel.ChunkRequest\x1a\x18.sentinel.ReviewResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNKREQUEST']._serialized_start=30
  _globals['_CHUNKREQUEST']._serialized_end=174
  _globals['_REVIEWRESPONSE']._serialized_start=177
  _globals['_REVIEWRESPONSE']._serialized_end=395
  _globals['_INFERENCESERVICE']._serialized_start=397
  _globals['_INFERENCESERVICE']._serialized_end=480
# @@protoc_insertion_point(module_scope)
